# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from events_pb2 import (
    Event as events_pb2___Event,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class EventBuffer(google___protobuf___message___Message):

    @property
    def event(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[events_pb2___Event]: ...

    def __init__(self,
        event : typing___Optional[typing___Iterable[events_pb2___Event]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> EventBuffer: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"event"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"event"]) -> None: ...
